import {
  Wand2,
  Sparkles,
  Zap,
  Flame,
  Rocket,
  Hammer,
  Wrench,
  Scissors,
  Eraser,
  Filter,
  SortAsc,
  AlignLeft,
  Type,
  Code2,
  FileText,
  ArrowDownAZ,
  CaseSensitive,
  Replace,
  Minimize2,
  Maximize2,
  Copy,
  ArrowUpDown,
  Hash,
  Shuffle,
  WrapText,
  AlignJustify,
  IndentIncrease,
  FileSearch,
  FilterX,
  ListX,
  Strikethrough,
  FileCode,
  Languages,
  AlignCenter,
  Calculator,
  PlusSquare,
  Link,
  Quote,
} from 'lucide-react'
import type { FormatterOperation } from './types'

export const COMMON_ICONS = [
  { icon: Wand2, label: 'Wand' },
  { icon: Sparkles, label: 'Sparkles' },
  { icon: Zap, label: 'Zap' },
  { icon: Flame, label: 'Flame' },
  { icon: Rocket, label: 'Rocket' },
  { icon: Hammer, label: 'Hammer' },
  { icon: Wrench, label: 'Wrench' },
  { icon: Scissors, label: 'Scissors' },
  { icon: Eraser, label: 'Eraser' },
  { icon: Filter, label: 'Filter' },
  { icon: SortAsc, label: 'Sort' },
  { icon: AlignLeft, label: 'Align' },
  { icon: Type, label: 'Text' },
  { icon: Code2, label: 'Code' },
  { icon: FileText, label: 'File' },
]

export const OPERATIONS: FormatterOperation[] = [
  // Lines
  {
    id: 'trim',
    name: 'Trim Whitespace',
    icon: 'Scissors',
    category: 'Text',
    description: 'Remove leading/trailing whitespace',
    defaultConfig: { lines: true },
  },
  {
    id: 'filter-lines',
    name: 'Remove Empty Lines',
    icon: 'Filter',
    category: 'Lines',
    description: 'Remove empty or whitespace-only lines',
    defaultConfig: { trim: false },
  },
  {
    id: 'sort-lines',
    name: 'Sort Lines',
    icon: 'ArrowDownAZ',
    category: 'Lines',
    description: 'Sort lines alphabetically or numerically',
    defaultConfig: { direction: 'asc', numeric: false },
  },
  {
    id: 'join-lines',
    name: 'Join Lines',
    icon: 'Minimize2',
    category: 'Structure',
    description: 'Join all lines into one',
    defaultConfig: { separator: ' ' },
  },
  {
    id: 'split-lines',
    name: 'Split Lines',
    icon: 'Maximize2',
    category: 'Structure',
    description: 'Split text into lines by separator',
    defaultConfig: { separator: ',' },
  },
  {
    id: 'dedupe-lines',
    name: 'Remove Duplicates',
    icon: 'Copy',
    category: 'Lines',
    description: 'Remove duplicate lines',
    defaultConfig: { keep: 'first', caseSensitive: true },
  },
  {
    id: 'reverse-lines',
    name: 'Reverse Lines',
    icon: 'ArrowUpDown',
    category: 'Lines',
    description: 'Flip line order',
    defaultConfig: {},
  },
  {
    id: 'number-lines',
    name: 'Number Lines',
    icon: 'Hash',
    category: 'Lines',
    description: 'Add line numbers',
    defaultConfig: { prefix: '', separator: '. ', start: 1 },
  },
  {
    id: 'shuffle-lines',
    name: 'Shuffle Lines',
    icon: 'Shuffle',
    category: 'Lines',
    description: 'Randomize line order',
    defaultConfig: {},
  },
  // Text
  {
    id: 'change-case',
    name: 'Change Case',
    icon: 'CaseSensitive',
    category: 'Text',
    description: 'Convert text case (Upper, Lower, Title, etc.)',
    defaultConfig: { mode: 'upper', lines: true },
  },
  {
    id: 'wrap-lines',
    name: 'Wrap Lines',
    icon: 'WrapText',
    category: 'Structure',
    description: 'Add prefix/suffix to each line',
    defaultConfig: { prefix: '', suffix: '' },
  },
  {
    id: 'word-wrap',
    name: 'Word Wrap',
    icon: 'AlignJustify',
    category: 'Structure',
    description: 'Wrap lines at width',
    defaultConfig: { width: 80 },
  },
  {
    id: 'indent',
    name: 'Indent/Dedent',
    icon: 'IndentIncrease',
    category: 'Text',
    description: 'Add/remove leading whitespace',
    defaultConfig: { mode: 'indent', size: 2, useTabs: false },
  },
  {
    id: 'extract-matches',
    name: 'Extract Matches',
    icon: 'FileSearch',
    category: 'Search',
    description: 'Extract all regex matches',
    defaultConfig: { pattern: '', caseInsensitive: false },
  },
  {
    id: 'keep-lines',
    name: 'Keep Lines Matching',
    icon: 'FilterX',
    category: 'Search',
    description: 'Keep lines matching pattern',
    defaultConfig: { pattern: '', regex: false, caseInsensitive: false },
  },
  {
    id: 'remove-lines',
    name: 'Remove Lines Matching',
    icon: 'ListX',
    category: 'Search',
    description: 'Remove lines matching pattern',
    defaultConfig: { pattern: '', regex: false, caseInsensitive: false },
  },
  {
    id: 'remove-chars',
    name: 'Remove Characters',
    icon: 'Strikethrough',
    category: 'Search',
    description: 'Strip specific characters',
    defaultConfig: { mode: 'digits' },
  },
  {
    id: 'encode-decode',
    name: 'Encode/Decode',
    icon: 'FileCode',
    category: 'Data',
    description: 'URL, Base64, HTML entities',
    defaultConfig: { mode: 'url-encode' },
  },
  {
    id: 'escape',
    name: 'Escape/Unescape',
    icon: 'Languages',
    category: 'Data',
    description: 'JSON/Regex escape',
    defaultConfig: { mode: 'json-escape' },
  },
  {
    id: 'pad-align',
    name: 'Pad/Align',
    icon: 'AlignCenter',
    category: 'Text',
    description: 'Pad to fixed width',
    defaultConfig: { width: 20, align: 'left', char: ' ' },
  },
  {
    id: 'format-numbers',
    name: 'Format Numbers',
    icon: 'Calculator',
    category: 'Data',
    description: 'Thousands/decimal formatting',
    defaultConfig: { thousands: true, decimals: 2 },
  },
  {
    id: 'increment-numbers',
    name: 'Increment Numbers',
    icon: 'PlusSquare',
    category: 'Data',
    description: 'Find/increment numbers',
    defaultConfig: { delta: 1 },
  },
  {
    id: 'slugify',
    name: 'Slugify',
    icon: 'Link',
    category: 'Text',
    description: 'Convert to URL slug',
    defaultConfig: { lines: true },
  },
  {
    id: 'quote',
    name: 'Quote/Unquote',
    icon: 'Quote',
    category: 'Text',
    description: 'Add/remove quotes',
    defaultConfig: { mode: 'add', char: '"', lines: true },
  },
  {
    id: 'replace',
    name: 'Replace Text',
    icon: 'Replace',
    category: 'Search',
    description: 'Find and replace text',
    defaultConfig: { from: '', to: '', regex: false, caseInsensitive: false, lines: true },
  },
]

export const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  // Common Icons
  Wand: Wand2,
  Sparkles,
  Zap,
  Flame,
  Rocket,
  Hammer,
  Wrench,
  Scissors,
  Eraser,
  Filter,
  Sort: SortAsc,
  Align: AlignLeft,
  Text: Type,
  Code: Code2,
  File: FileText,
  // Operation Icons
  ArrowDownAZ,
  CaseSensitive,
  Replace,
  Minimize2,
  Maximize2,
  Copy,
  ArrowUpDown,
  Hash,
  Shuffle,
  WrapText,
  AlignJustify,
  IndentIncrease,
  FileSearch,
  FilterX,
  ListX,
  Strikethrough,
  FileCode,
  Languages,
  AlignCenter,
  Calculator,
  PlusSquare,
  Link,
  Quote,
}
